---
- name: "Create the service configuration file"
  copy:
    content: "{{ docker__configuration | to_nice_json(indent=4) }}"
    dest: "{{ docker__config_file }}"
    owner: "{{ docker__user }}"
    group: "{{ docker__group }}"
    mode: "{{ docker__file_mode }}"
  notify: Restart docker service
...
