---
- name: Start the service and enable it
  systemd:
    name: "{{ docker__service }}.service"
    enabled: true
    state: started
  register: docker__service_started

- name: Set logrotate__installed flag
  set_fact:
    docker__skip_installation: true
...
